module.exports.sellerSchema = require('./seller.model')
module.exports.userSchema = require('./user.model')
module.exports.productSchema = require('./product.model')
module.exports.wishListSchema = require('./wishList.model')
module.exports.cardSchema = require('./card.model')
module.exports.paymemtSchema = require('./payment.model')