module.exports.adminSchema = require('./admin.model')
module.exports.userSchema = require('./user.model')
module.exports.citySchema = require('./city.model')
module.exports.categorieSchema = require('./categories.model')
module.exports.foodItemSchema = require('./foodItem.model')
module.exports.deliveryDriverSchema = require('./deliveryDriver.model')